# 项目 api 环境变量配置
project:
  baseUrl: http://192.168.1.117:8090
  YunServicesUrl: http://192.168.1.176:15000
  basicplatform: http://192.168.1.238:8080/nsbi/
# iframe嵌套初始化地址
initCfg:
  initUrl: "basicplatform-highgis-portal/main.html#/userCenter"

# 项目信息配置
system:
  title: vue-cli # 应用程序标题
  introduction: TopHighGIS高性能云GIS平台是湖北金拓维信息技术有限公司开发的，具有完全自主知识产权的GIS平台产品. # 应用程序描述信息
  copyright: Copyright &copy; 2019 湖北金拓维信息技术有限公司 # 版权信息
  logoUrl: static/images/brand.jpg # LOGO 图片
  expiredTime: 5 # 登录过期时间(单位:小时)

# websocket服务地址
socket: http://192.168.1.68:8020

# raven服务监控地址
#  key: raven服务生成的唯一key
#  sentryUrl: sentry服务部署的地址
#  project: sentry中创建的项目名称
#  例子： https://${key}@${sentryUrl}/${project}

raven: https://${key}@${sentryUrl}/${project}

# 系统路由配置
# 详情见： https://router.vuejs.org/zh-cn/api/options.html#routes
# 路由白名单 匹配该路径的地址将不会被校验权限
whiteList:
  - "/login"
  - "/register"
# 异步权限路由
# 示例：
# routes:
#   RtBase:
#     path: "/"
#     component: "view/components/RtBase"
#     redirect: "/pap"
#     children:
#       # HelloWorld:
#       #   path: "/pap"
#       #   component: "view/components/HelloWorld"
#       Rtzty:
#         path: "/rtzty"
#         component: "view/components/Rtzty"
#   RtMap:
#     path: "/map"
#     componet: "view/componets/RtMap"
#     children:
#       Vue-cli:
#         path: "/vue-cli"
#         componet: "view/componets/Vuecli"
